### ISSUE TITLE
BAP tester

### ISSUE THREAD

**Issue by OneB1t** [adi961/mib2-android-auto-vc#6]
Is there some way to create class which will send all available BAP commands to VC in loop? To see what is even possible to change and what messages are supported :-). I know for example that VC can show ad-hoc TMC message and maybe that can be used for some other usefull data like oil temp reached.

**Comment by adi961** [comment]
I dont think that is easily done because the BAP mesages have different parameters. But you can see the BAP messages which can be sent from the MIB in the lsd.jxe in the package `de.vw.mib.bap.mqbab2.audiosd.functions`, `de.vw.mib.bap.mqbab2.navsd.functions` and `de.vw.mib.bap.mqbab2.telephone2.functions`.

I also tried a bit to find something tho show messages in the VC. the only thing I found was to use `ASLNavBAPFactory.getNavBAPApi().updateBapTMCInfo()` to send a message to VC. The issue I had was that every time a message is sent the dashboard does a chime. Which is quite annoying if the message is not critical.

I think ideal would be if it is somehow possible to put a message in the little popup which is uses e.g. when the drive mode is changed.
